### ISSUE TITLE
static ip address

### ISSUE THREAD

**Issue by tsouhaieb** [hypriot/image-builder-rpi#159]
how to fix ip address, on raspbian jessy i normally edit /etc/dhcpcd.conf file,
but in hypriot os this file doesn't exist and even if i create it and edit i, the change in it does not take effect even after reboot, how we can fix and change fixed ip address on hypriotos, sorry for the bothering and thanks for this great work,

Salam,
Peace

**Comment by carljmosca** [comment]
check /etc/network/interfaces.d for your interface(s)

**Comment by firecyberice** [comment]
Currently we do not have dhcpcd installed by default so creating `/etc/dhcpcd.conf` has no effect.

**Comment by tsouhaieb** [comment]
i already find a way, you can check [device-init#6](https://github.com/hypriot/device-init/issues/6)

**Comment by StefanScherer** [comment]
We have switched to cloud-init. 
Cloud-init normally does static IP with other files, but then you need the MAC address of your Pi. But what if you want to unbox a fresh RPi and flash and boot it?

With cloud-init there is another hacky way to write the information into `/boot/user-data` file

```yaml
#cloud-config
# vim: syntax=yaml
#

# Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
hostname: static
manage_etc_hosts: true
# don't write debian.org into apt mirrors
apt_preserve_sources_list: true

# You could modify this for your own user information
users:
  - name: pirate
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    plain_text_passwd: hypriot
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

package_upgrade: false

# Static IP address
write_files:
  - content: |
      persistent
      # Generate Stable Private IPv6 Addresses instead of hardware based ones
      slaac private

      # static IP configuration:
      interface eth0
      static ip_address=192.168.1.31/24
      #static ip6_address=fd51:42f8:caae:d92e::ff/64
      static routers=192.168.1.1
      static domain_name_servers=192.168.1.1 8.8.8.8

    path: /etc/dhcpcd.conf
```
