### ISSUE TITLE
cannot boot 1.9.0 image on RPI 1

### ISSUE THREAD

**Issue by eyakcn** [hypriot/image-builder-rpi#258]
I see the description that 1.9.0 release works on all Raspberry Pi models (1, 2, 3, 3 B+, Zero, Zero W & Compute Module) as the Docker Engine 18.04.0-ce is built for ARMv6

My Raspberry PI was bought in 2014, maybe it's RPI 1.

Anyway, after the image flashed into the SD card, it can not boot. The board never light on except the power. I tried to give it HDMI output, but nothing happens.

Here is the user-data I used:

#cloud-config
hostname: rasp512
manage_etc_hosts: true

users:
  \- name: peter
    gecos: "Peter SONG"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video,input
    plain_text_passwd: xxxxxxxx
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

locale: "zh_CN.UTF-8"

timezone: "Asia/Shanghai"

package_update: false
package_upgrade: false

write_files:
  \- content: |
      {
        "registry-mirrors": ["https://registry.docker-cn.com"]
      }
    path: /etc/docker/daemon.json

runcmd:
  \- systemctl restart avahi-daemon
  \- systemctl restart docker

**Comment by StefanScherer** [comment]
Hey @eyakcn 
I tried your cloud-init yml file and flashed a 1.9.0 SD image and booted a Raspberry Pi 1 from 2012. 
On HDMI output you should see the resize filesystem dialog, then the pi reboots and logs its boot steps and cloud-init steps.
As you cannot see anything please check if you have flashed the SD image correctly.
There should be a FAT partition after flashing it and that partition is visible on a Windows or Mac computer.

You can also check you cloud-init file which is a YAML and sometimes hard to get the indenation right.
On my Mac I could use this line to verify the YML file.

```
ruby -e "require 'yaml';YAML.load_file('./issue258.yml'); puts 'YAML is ok'"
```

or use an online yaml validator https://coreos.com/validate/


The correct indented cloud-init file that works for me is:

```yaml
#cloud-config

hostname: rasp512
manage_etc_hosts: true

users:
  - name: peter
    gecos: "Peter SONG"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video,input
    plain_text_passwd: xxxxxxxxxx
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

locale: "zh_CN.UTF-8"

timezone: "Asia/Shanghai"

package_update: false
package_upgrade: false

write_files:
  - content: |
      {
      "registry-mirrors": ["https://registry.docker-cn.com"]
      }
    path: /etc/docker/daemon.json

runcmd:
  - 'systemctl restart avahi-daemon'
  - 'systemctl restart docker'
```
