### ISSUE TITLE
Permission problems with docker-compose

### ISSUE THREAD

**Issue by Jacobh2** [hypriot/image-builder-rpi#261]
Hi!

I'm trying to use rabbit MQ on a RPi 3 using Hypriot 1.9.0 via docker-compose!
My docker-compose file looks like this:
```
version: '3'
services:
  rabbitmq:
    image: arm32v7/rabbitmq:3.7.7-management
    restart: always
    hostname: rpi-test-client
    environment:
      - RABBITMQ_LOG_BASE=/tmp
      - RABBITMQ_LOGS=rabbitmq.log
      - RABBITMQ_NODENAME=rpi-test-client
    volumes: 
      - ./data_rabbitmq:/var/lib/rabbitmq/mnesia
      - ./logs:/tmp
```
but after running `docker-compose up -d` it crashes with the log
```
BOOT FAILED
===========

Error description:
    init:do_boot/3
    init:start_em/1
    rabbit:start_it/1 line 450
    rabbit:'-boot/0-fun-0-'/0 line 298
    rabbit:start_logger/0 line 928
    rabbit_lager:ensure_log_working/0 line 115
    rabbit_lager:'-ensure_log_working/0-lc$^0/1-0-'/1 line 115
    rabbit_lager:ensure_logfile_exist/1 line 158
throw:{error,{cannot_log_to_file,"/tmp/rabbitmq.log",enoent}}
{"init terminating in do_boot",{error,{cannot_log_to_file,"/tmp/rabbitmq.log",enoent}}}
init terminating in do_boot ({error,{cannot_log_to_file,/tmp/rabbitmq.log,enoent}})

Crash dump is being written to: /tmp/erl_crash.dump...
```
This compose file works when I'm testing it in docker for mac, but not on the pi.  The `{cannot_log_to_file,"/tmp/rabbitmq.log",enoent}` part suggests that the file does not exist, so I've also tried to create it before running `docker-compose up -d` on the pi but it does not help.

My thoughts are that when I do `docker-compose up -d` that is being run by root and not the pirate user, and that has something to do with the permissions to the log-file. So with that in mind, is it possible to change so that it isn't root that is starting up the containers?
