### ISSUE TITLE
ERROR: for [name]  Cannot start service [service]: OCI runtime start failed: container process is already dead: unknown

### ISSUE THREAD

**Issue by paulomcnally** [hypriot/image-builder-rpi#305]
```
hypriotos-rpi-v1.10.0.img.zip
```

```
$ docker -v
Docker version 18.06.3-ce, build d7080c1
```

Error message:
```
ERROR: for [name]  Cannot start service [service]: OCI runtime start failed: container process is already dead: unknown
```

docker-compose.yml
```
version: '3'

services:
  postgres:
    image: postgres:11.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD:
  redis:
    image: redis:5.0.3
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
  mongo:
    image: amd64/mongo:4.1-xenial
    ports:
      - 27017:27017
```

## Solutions

https://success.docker.com/article/error-oci-runtime-create-failed-docker-1809
