### ISSUE TITLE
Issue with setting up eth0 with static ip address

### ISSUE THREAD

**Issue by dennym** [hypriot/image-builder-rpi#366]
I gave Hypriot-1.12.2 and run today and configured cloud-init config and everything got flashed and initialized correctly with your provided flash tool.

Unfortunately the static ip address for eth0 does and won't work. I tried the example from  https://github.com/hypriot/flash/tree/master/sample/static.yml .

```
write_files:
  - content: |
      persistent
      slaac private
      interface eth0
      static ip_address=192.168.0.31/24
      static routers=192.168.0.1
      static domain_name_servers=192.168.0.1 8.8.8.8
    path: /etc/dhcpcd.conf
```

After the PIs are up and running I checked via ssh if the file exists and `/etc/dhcpcd.conf` exists with the mentioned content. Since it wasn't applied to the network I though about restarting the service with `sudo service dhcpcd restart` but this service is masked and can't be actually used. As far I am aware if something is masked its unused and dead. Since the example are quite old I guess a lot of stuff changed since then. Is there another approach for this?

best

**Comment by rbartoli** [comment]
I reported same issue in #359 and I've still not found the solution.

**Comment by p-hagen-Signalfx** [comment]
In the root of your SD card, there is a file called network-config
this is where you set the settings that get used during cloud-config
This is what is in mine, and this works:

```
version: 1
config:
  - type: physical
    name: eth0
    subnets:
      - type: static
        address: 192.168.1.10/24
        gateway: 192.168.1.1
  - type: nameserver
    address:
      - 192.168.1.1
```
